# Generated by Django 5.0.6 on 2024-06-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('birth_year', models.IntegerField()),
                ('phone_num', models.CharField(max_length=20)),
                ('note', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
