# Generated by Django 5.0.6 on 2024-06-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='birth_year',
        ),
    ]
