# Generated by Django 5.0.6 on 2024-06-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0004_alter_appointment_options_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
