# Generated by Django 5.0.6 on 2024-06-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0008_diagnosis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ('appointment',), 'verbose_name_plural': 'Diagnosis'},
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='disease',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='patient',
        ),
    ]
